define({
        "1":{
            value:"BlockedShots",
            cnValue:"射门被挡",
        },
        "2":{
            value:"YellowCards",
            cnValue:"黄牌",
        },
        "3":{
            value:"SecondYellowCards",
            cnValue:"二次黄牌",
        },
        "4":{
            value:"SraightRedCards",
            cnValue:"红牌",
        },
        "5":{
            value:"ShotsOnTarget",
            cnValue:"射正",
        },
        "6":{
            value:"ShotsOffTarget",
            cnValue:"射偏",
        },
        "7":{
            value:"Corners",
            cnValue:"角球",
        },
        "8":{
            value:"PenaltiesAwarded",
            cnValue:"点球",
        },
        "9":{
            value:"Offsides",
            cnValue:"越位",
        },
        "10":{
            value:"GoalKicks",
            cnValue:"球门球",
        },
        "11":{
            value:"MissedPenalties",
            cnValue:"点球未中",
        },
        "12":{
            value:"ThrowIns",
            cnValue:"界外球",
        }
})